spring:
  application:
    name: ai-agent
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.179.127:3306/ai_agent
    username: root
    password: 123
  # redis 配置
  data:
    redis:
      host: 192.168.179.127
      port: 6379
      ttl: 3600
      database: 0
  profiles:
    active: local

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # ??????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段(isDelete)
      logic-delete-value: 1 # ?????????????? 1
      logic-not-delete-value: 0 # ?????????????? 0
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xhh.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

